export const colorLookup: { [key: string]: string } = {
  gray: "gray",
  grey: "gray",
  red: "bg-red-600",
  white: "white",
  teal: "teal",
  purple: "purple",
  green: "bg-green-700",
  blue: "bg-blue-700",
  black: "bg-black",
  orange: "bg-orange-400",
  satin_nickel: "bg-gray-300",
  matte_black: "bg-black",
  venetian_bronze: "bg-amber-800",
  polished_chrome: "bg-gray-100",
  lifetime_polished_brass: "bg-yellow-400",
  antique_nickel: "bg-gray-400",
  "combo-other": "bg-gradient-to-r from-gray-300 to-amber-700", // or "bg-gray-500"  
  antique_brass: "bg-amber-600",
  polished_brass: "bg-yellow-300",
  satin_chrome: "bg-gray-200",
  spot_defense_brushed_nickel: "bg-gray-400",
  spot_defense_matte_black: "bg-black",
  brushed_gold: "bg-yellow-500",
  "combo-matte_black_and_brushed_gold": "bg-gradient-to-r from-black to-yellow-500",
  tuscan_bronze: "bg-amber-900",
  brushed_nickel: "bg-gray-300",
};
